/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
    './hooks/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#6EC1E4',
        secondary: '#A6E3C1',
        accent: '#C5B4E3',
        bgLight: '#F7F8FA',
        bgDark: '#1E1E2F',
        cardLight: '#FFFFFF',
        cardDark: '#2A2A3D',
        textPrimary: '#1A1A1A',
        textSecondary: '#666666',
        alert: '#F66A6A',
        success: '#4CAF50',
        info: '#F9E79F',
        neutralLine: '#CCCCCC',
        inputBorder: '#E0E0E0',
        inputPlaceholder: '#999999',
        disabled: '#CCCCCC',
      },
      spacing: {
        xs: '4px',
        s: '8px',
        m: '16px',
        l: '24px',
        xl: '32px',
        xxl: '48px',
      },
      fontFamily: {
        body: ['Poppins_400Regular'],
        medium: ['Poppins_500Medium'],
        semibold: ['Poppins_600SemiBold'],
        bold: ['Poppins_700Bold'],
      },
      fontSize: {
        headline: ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        subheadline: ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'subheadline-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        body: ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        button: ['16px', { lineHeight: '22px', fontWeight: '500' }],
        'button-lg': ['18px', { lineHeight: '24px', fontWeight: '500' }],
      },
      borderRadius: {
        button: '12px',
        card: '16px',
        input: '12px',
      },
      boxShadow: {
        card: '0px 2px 6px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
};
