export const preventionTheme = {
  colors: {
    light: {
      primary: "#6EC1E4",
      secondary: "#A6E3C1",
      accent: "#C5B4E3",
      background: "#F7F8FA",
      card: "#FFFFFF",
      textPrimary: "#1A1A1A",
      textSecondary: "#666666",
      inputBorder: "#E0E0E0",
      inputPlaceholder: "#999999",
      disabled: "#CCCCCC",
      baseline: "#CCCCCC",
      error: "#F66A6A",
      success: "#4CAF50",
      info: "#F9E79F",
      tabIconDefault: "#666666",
      tabIconSelected: "#6EC1E4",
    },
    dark: {
      primary: "#6EC1E4",
      secondary: "#A6E3C1",
      accent: "#C5B4E3",
      background: "#1E1E2F",
      card: "#2A2A3D",
      textPrimary: "#E0E0E0",
      textSecondary: "#B5B5C3",
      inputBorder: "#3D3D52",
      inputPlaceholder: "#8A8AA3",
      disabled: "#666680",
      baseline: "#666680",
      error: "#F66A6A",
      success: "#4CAF50",
      info: "#F9E79F",
      tabIconDefault: "#B5B5C3",
      tabIconSelected: "#6EC1E4",
    },
    gradients: {
      calmAi: ["#6EC1E4", "#A6E3C1", "#C5B4E3"],
    },
  },
  typography: {
    family: {
      body: "Poppins_400Regular",
      medium: "Poppins_500Medium",
      semiBold: "Poppins_600SemiBold",
      bold: "Poppins_700Bold",
    },
    size: {
      headlineLg: 32,
      headline: 24,
      subheadlineLg: 20,
      subheadline: 18,
      bodyLg: 16,
      body: 14,
      caption: 12,
      buttonLg: 18,
      button: 16,
    },
    lineHeight: {
      headlineLg: 38,
      headline: 30,
      subheadlineLg: 28,
      subheadline: 24,
      bodyLg: 24,
      body: 22,
      caption: 16,
      buttonLg: 24,
      button: 22,
    },
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 12,
    md: 16,
  },
  shadow: {
    card: {
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 2,
    },
  },
} as const;
